name: DontRP
version: 1.4
main: com.github.dont65.dontrp.DontRP
api-version: 1.21
authors: [Dont65]
softdepend: [PlaceholderAPI]
permissions:
  dontrp.rpname_color.admin:
    description: Позволяет менять цвет имени через HEX
    default: op
  dontrp.admin:
    description: Полный доступ
    default: op
commands:
  rpname: { description: "Manage RP Name" }
  me: { description: "Action" }
  do: { description: "Describe" }
  try: { description: "Try" }
  todo: { description: "Talk and do" }
  roll: { description: "Roll dice" }
  rp: { description: "Settings" }
  description: { description: "Character bio", aliases: [desc] }
  adm: { description: "Admin commands" }
